### PR TITLE
Modify module path to include major version

### PR DESCRIPTION
**Pull request by john-d8r**
## Related issues
- Close #XXX

## Related PRs
- [ ] #XXX
- [ ] #YYY

Remove this section if you don't have related PRs.

## Checklist
- [ ] I've read the [guidelines for contributing](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/) to this repository.
- [ ] I've followed the [conventions](https://aquasecurity.github.io/trivy/latest/community/contribute/pr/#title) in the PR title.
- [ ] I've added tests that prove my fix is effective or that my feature works.
- [ ] I've updated the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs) with the relevant information (if needed).
- [ ] I've added usage information (if the PR introduces new options)
- [ ] I've included a "before" and "after" example to the description (if the PR is a user interface change).

### CODE REVIEW

**Comment by oberg-s** [comment]
@d5n & @namandf  , What are your thoughts on updating the go module package structure to `v3` vs `v2` in this repo?   i.e. this repo could be versioned independent of deepfactor repo API v3, **if** there is a need to do so. However, tracking different Go module api versions between separate components we ship can be confusing. So, at the moment I am in agreement with John's proposal to version this module's major version to  `v3`.  Let us know if there are other considerations. Thanks.

**Comment by namandf** [comment]
> @d5n & @namandf , What are your thoughts on updating the go module package structure to `v3` vs `v2` in this repo? i.e. this repo could be versioned independent of deepfactor repo API v3, **if** there is a need to do so. However, tracking different Go module api versions between separate components we ship can be confusing. So, at the moment I am in agreement with John's proposal to version this module's major version to `v3`. Let us know if there are other considerations. Thanks.

Hi @oberg-s , My only concern with this approach (applies to deepfactor repo as well) is the need to ensure we revisit this each time we move to a different major version. If we are fine doing that, then John's changes seems fine.
An alternative approach could be keep the module name same and use the `+incompatible` suffix in the version added to go mod. That will suppress the semantic versioning error.

**Review by oberg-s — CHANGES_REQUESTED** [review]
This this repo is a fork of trivy and we need to incorporate upstream patches/branches, we should not fork the go module structure for pkg without a very good reason. Let's discuss if this change is required and worth the long term maintenance issues that it will incur.

**Comment by oberg-s** [comment]
> we should not fork the go module structure for pkg without a very good reason.

I did not realize that this diff only renames imports and does not move the contents of the pkg directory. However, there will still be a non-trivial amount of work to fix up imports on upstream merge. e.g. whenever imports are reordered or added in any .go file that utilizes the local `pkg` there will be a conflict.  Manually resolving each conflict could be avoided if we have a two phase merge to avoid hundreds of expected conflicts from upstream.

Phase 1: fetch remote branch, fork branch as branch-pkgv3, update all imports in *.go to pkg/v3 (script), commit 
Phase 2: merge branch-pkgv3 to DF sprint branch

@john-d8r , please go through this two phase merge process for the pending PR branch 3.9-DEEP-11079 and we'll see if the two phase approach works without requiring manual conflict resolution. Alternatively, if PR 84 is stale, sync a new upstream version/branch after conferring with your team.
https://github.com/deepfactor-io/trivy/pull/84/files

@namandf, please provide your review of this remediation strategy.

**Comment by namandf** [comment]
> I did not realize that this diff only renames imports and does not move the contents of the pkg directory. However, there will still be a non-trivial amount of work to fix up imports on upstream merge. e.g. whenever imports are reordered or added in any .go file that utilizes the local pkg there will be a conflict. Manually resolving each conflict could be avoided if we have a two phase merge to avoid hundreds of expected conflicts from upstream.
> 
> Phase 1: fetch remote branch, fork branch as branch-pkgv3, update all imports in *.go to pkg/v3 (script), commit
> Phase 2: merge branch-pkgv3 to DF sprint branch
> 
> @john-d8r , please go through this two phase merge process for the pending PR branch 3.9-DEEP-11079 and we'll see if the two phase approach works without requiring manual conflict resolution. Alternatively, if PR 84 is stale, sync a new upstream version/branch after conferring with your team.
> https://github.com/deepfactor-io/trivy/pull/84/files
> 
> @namandf, please provide your review of this remediation strategy.

Hi @oberg-s , we intend to merge PR 84 in 3.10. I'll mark it as draft. So John's change might be good for now. But yes, we can follow the approach you suggested going forward.

**Comment by john-d8r** [comment]
Hi @oberg-s, as Naman suggested we will follow the two step process going forward. 

Since we have not planned to sync with upstream in 3.9, let us know if this PR is good to be merged in its current state.

**Comment by oberg-s** [comment]
I have no more reservations on this PR. I will approve as a 2nd once I see that someone else has reviewed.

**Review by namandf — APPROVED** [review]

**Review by oberg-s — APPROVED** [review]
My concerns w.r.t. approval are resolved.

**Pull request merged**
